### ISSUE TITLE
how to register and enroll user with someother organisation afflilation

### ISSUE THREAD

**Issue by adityainterwork** [IBM/raft-fabric-sample#13]
I am trying to register a user for org2 and facing issue.

**Comment by horeaporutiu** [comment]
@adityainterwork 

Just made a new commit to address this issue - https://github.com/IBM/raft-fabric-sample/commit/759f82e94f9d94960b75a27c91fe2dda4bc0684f

Pull the latest code, clean your docker setup, and then try to register again. should work now.

**Comment by adityainterwork** [comment]
Actually I have fixed that issue. Now register the user in any org just by first creating the affiliation and then registering them to the network. Also, I have been using CA servers from the **docker-compose-ca.yaml**

**Comment by horeaporutiu** [comment]
perfect - you have used some logic similar to `enrollAdmin.js`?

**Comment by adityainterwork** [comment]
Yes, First create the affiliation for the org in which you want to register and enroll a user. After that, you can simply enroll and register the user for that org.

**Comment by horeaporutiu** [comment]
Great - thank you. Closing the issue now.
