### ISSUE TITLE
Error on npm install client

### ISSUE THREAD

**Issue by AjeethT** [IBM/raft-fabric-sample#20]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tar@2.2.1 (node_modules/tar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting tar@2.2.1:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting tar@2.2.1:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-jk0qJWwOIYXGsYrWlK7JaLg8sdE= integrity checksum failed when using sha1: wanted sha1-jk0qJWwOIYXGsYrWlK7JaLg8sdE= but got sha512-g2SVs5QIxvo6OLp0GudTqEf05maawKUxXru104iaayWA09551tFCTI8f1Asb4lPfkBr91k07iL4c11XO3/b0tA== sha1-lGsoELml4LJhQM94vqawsNaJ66E=. (35214 bytes)

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting js-yaml@3.13.0:
npm ERR! Verification failed while extracting js-yaml@3.13.0:
npm ERR! sha512-pZZoSxcCYco+DIKBTimr67J6Hy+EYGZDY/HCWC+iAEA9h1ByhMXAIVUXMcMFpOCxQ/xjXmPI2MkDL5HRm5eFrQ== integrity checksum failed when using sha512: wanted sha512-pZZoSxcCYco+DIKBTimr67J6Hy+EYGZDY/HCWC+iAEA9h1ByhMXAIVUXMcMFpOCxQ/xjXmPI2MkDL5HRm5eFrQ== but got sha512-YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==. (74050 bytes)

**Comment by horeaporutiu** [comment]
@AjeethT Still having this problem?

**Comment by richardpatsch** [comment]
Had the same issue today, but suggestion in #19 solved it for me.
(delete package-lock.json and node_modules folder)

node: v10.16.0
npm: 6.14.4

**Comment by horeaporutiu** [comment]
Thanks for updating @richardpatsch
