### ISSUE TITLE
Failed to enroll admin user: admin TypeError: FileSystemWallet is not a constructor

### ISSUE THREAD

**Issue by LukasJaks** [IBM/raft-fabric-sample#28]
When I ran enrollAdmin.js using node from web-app/server it gives me an error: Failed to enroll admin user: admin TypeError: FileSystemWallet is not a constructor.

**Comment by iman-hussain** [comment]
Have had the same issue for the past few days, issue is present on Windows and Linux machine,  will update with logs in the morning

**Comment by LukasJaks** [comment]
Was user error. permissions should be left on default (I did chmod -R 777 on the whole folder).
